<?php

namespace ContainerPFkdi9G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GvlM2ghService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GvlM2gh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GvlM2gh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileUploader' => ['privates', 'App\\Services\\FileUploader', 'getFileUploaderService', true],
            'product' => ['privates', '.errored..service_locator.GvlM2gh.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.GvlM2gh": it references class "App\\Entity\\Product" but no such service exists.'],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', false],
        ], [
            'fileUploader' => 'App\\Services\\FileUploader',
            'product' => 'App\\Entity\\Product',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'validator' => '?',
        ]);
    }
}
