<?php

namespace ContainerPFkdi9G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E7BAULIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E7BAULI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E7BAULI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::create' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Controller\\CategoryController::destroy' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.BOF9k5a', 'get_ServiceLocator_BOF9k5aService', true],
            'App\\Controller\\HomeController::productCategories' => ['privates', '.service_locator.peBNs6U', 'get_ServiceLocator_PeBNs6UService', true],
            'App\\Controller\\ImageController::destroy' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController::create' => ['privates', '.service_locator._uCTTsk', 'get_ServiceLocator_UCTTskService', true],
            'App\\Controller\\ProductController::destroy' => ['privates', '.service_locator.517U8lX', 'get_ServiceLocator_517U8lXService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.GvlM2gh', 'get_ServiceLocator_GvlM2ghService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController::searchAction' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.3PNOaV8', 'get_ServiceLocator_3PNOaV8Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::create' => ['privates', '.service_locator.2w3znsa', 'get_ServiceLocator_2w3znsaService', true],
            'App\\Controller\\UserController::destroy' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.Y4EzA8m', 'get_ServiceLocator_Y4EzA8mService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CategoryController:create' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Controller\\CategoryController:destroy' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.BOF9k5a', 'get_ServiceLocator_BOF9k5aService', true],
            'App\\Controller\\HomeController:productCategories' => ['privates', '.service_locator.peBNs6U', 'get_ServiceLocator_PeBNs6UService', true],
            'App\\Controller\\ImageController:destroy' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController:create' => ['privates', '.service_locator._uCTTsk', 'get_ServiceLocator_UCTTskService', true],
            'App\\Controller\\ProductController:destroy' => ['privates', '.service_locator.517U8lX', 'get_ServiceLocator_517U8lXService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.GvlM2gh', 'get_ServiceLocator_GvlM2ghService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController:searchAction' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.3PNOaV8', 'get_ServiceLocator_3PNOaV8Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:create' => ['privates', '.service_locator.2w3znsa', 'get_ServiceLocator_2w3znsaService', true],
            'App\\Controller\\UserController:destroy' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.Y4EzA8m', 'get_ServiceLocator_Y4EzA8mService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CategoryController::create' => '?',
            'App\\Controller\\CategoryController::destroy' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::productCategories' => '?',
            'App\\Controller\\ImageController::destroy' => '?',
            'App\\Controller\\ProductController::create' => '?',
            'App\\Controller\\ProductController::destroy' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::searchAction' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::create' => '?',
            'App\\Controller\\UserController::destroy' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CategoryController:create' => '?',
            'App\\Controller\\CategoryController:destroy' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:productCategories' => '?',
            'App\\Controller\\ImageController:destroy' => '?',
            'App\\Controller\\ProductController:create' => '?',
            'App\\Controller\\ProductController:destroy' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:searchAction' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:create' => '?',
            'App\\Controller\\UserController:destroy' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
