<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPFkdi9G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPFkdi9G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPFkdi9G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPFkdi9G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPFkdi9G\App_KernelDevDebugContainer([
    'container.build_hash' => 'PFkdi9G',
    'container.build_id' => 'abf4bceb',
    'container.build_time' => 1611525448,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPFkdi9G');
